name: Generate PDF

on:
  push:
    paths:
      - index.html

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wkhtmltopdf

      - name: Generate PDF
        run: |
          wkhtmltopdf index.html output.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-report
          path: output.pdf
